name: Deploy Flutter Web with Supabase Secrets

# تشغيل عند كل push للفرع الرئيسي
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. نسخ المستودع
      - name: Checkout repository
        uses: actions/checkout@v3

      # 5. نشر على GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
